task :default => "lib/jssocket.jar"

SIGN = "tatsuya"
SRC = FileList["src/*.java", "src/ffm/*.java", "src/ffm/socket/*.java", "src/ffm/upnp/*.java", "src/ffm/js/*.java"]
OBJ = FileList["classes/ffm/JSocketApplet.class",
               "classes/ffm/*.class",
               "classes/ffm/socket/TCPSocket.class",
               "classes/ffm/socket/SocketListenThread.class",
               "classes/ffm/socket/SocketListenSubThread.class",
               "classes/ffm/mock/MockCallback.class",
               "classes/ffm/socket/*.class",
               "classes/ffm/upnp/*.class",
               "classes/ffm/js/*.class"]

rule '.class' => [proc {|tn| tn.sub(/\.class$/, '.java').sub(/^classes\//, 'src/') }] do |t|
  sh "javac -d ./classes -classpath ./src:./lib/plugin.jar #{t.source}"
end

file "lib/jssocket.jar" => OBJ do |t|
  sh "jar cf #{t.name} -C classes/ ."
  sh "jarsigner #{t.name} #{SIGN}"
end

task "spec" =>"lib/jssocket.jar" do
  Dir::glob("spec/*.rb") do |f|
    sh "set CLASSPATH=./lib/jssocket.jar:$CLASSPATH;jruby -S spec #{f}"
  end
end

task "commit" do
  sh "find . -name \\*~ | xargs rm"
  sh "git add ."
  sh "git commit -a"
end
